/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ExampleRouteImport } from './routes/example'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as ConsoleIndexRouteImport } from './routes/_console/index'
import { Route as ConsoleWorkOrdersRouteImport } from './routes/_console/work-orders'
import { Route as ConsoleSystemStatusRouteImport } from './routes/_console/system-status'
import { Route as ConsoleSettingsRouteImport } from './routes/_console/settings'
import { Route as ConsoleOperatorsRouteImport } from './routes/_console/operators'
import { Route as ConsoleBlueprintsRouteImport } from './routes/_console/blueprints'
import { Route as ConsoleAssetsRouteImport } from './routes/_console/assets'
import { Route as ConsoleBlueprintsIndexRouteImport } from './routes/_console/blueprints/index'
import { Route as ConsoleBlueprintsUploadRouteImport } from './routes/_console/blueprints/upload'
import { Route as ConsoleBlueprintsUnitsRouteImport } from './routes/_console/blueprints/units'
import { Route as ConsoleBlueprintsSubcontractorsRouteImport } from './routes/_console/blueprints/subcontractors'
import { Route as ConsoleBlueprintsStructureRouteImport } from './routes/_console/blueprints/structure'
import { Route as ConsoleBlueprintsUnitsUnitIdRouteImport } from './routes/_console/blueprints/units.$unitId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleRoute = ExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleWorkOrdersRoute = ConsoleWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSystemStatusRoute = ConsoleSystemStatusRouteImport.update({
  id: '/system-status',
  path: '/system-status',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleOperatorsRoute = ConsoleOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleBlueprintsRoute = ConsoleBlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAssetsRoute = ConsoleAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleBlueprintsIndexRoute = ConsoleBlueprintsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleBlueprintsRoute,
} as any)
const ConsoleBlueprintsUploadRoute = ConsoleBlueprintsUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ConsoleBlueprintsRoute,
} as any)
const ConsoleBlueprintsUnitsRoute = ConsoleBlueprintsUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => ConsoleBlueprintsRoute,
} as any)
const ConsoleBlueprintsSubcontractorsRoute =
  ConsoleBlueprintsSubcontractorsRouteImport.update({
    id: '/subcontractors',
    path: '/subcontractors',
    getParentRoute: () => ConsoleBlueprintsRoute,
  } as any)
const ConsoleBlueprintsStructureRoute =
  ConsoleBlueprintsStructureRouteImport.update({
    id: '/structure',
    path: '/structure',
    getParentRoute: () => ConsoleBlueprintsRoute,
  } as any)
const ConsoleBlueprintsUnitsUnitIdRoute =
  ConsoleBlueprintsUnitsUnitIdRouteImport.update({
    id: '/$unitId',
    path: '/$unitId',
    getParentRoute: () => ConsoleBlueprintsUnitsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/example': typeof ExampleRoute
  '/sign-in': typeof SignInRoute
  '/assets': typeof ConsoleAssetsRoute
  '/blueprints': typeof ConsoleBlueprintsRouteWithChildren
  '/operators': typeof ConsoleOperatorsRoute
  '/settings': typeof ConsoleSettingsRoute
  '/system-status': typeof ConsoleSystemStatusRoute
  '/work-orders': typeof ConsoleWorkOrdersRoute
  '/': typeof ConsoleIndexRoute
  '/blueprints/structure': typeof ConsoleBlueprintsStructureRoute
  '/blueprints/subcontractors': typeof ConsoleBlueprintsSubcontractorsRoute
  '/blueprints/units': typeof ConsoleBlueprintsUnitsRouteWithChildren
  '/blueprints/upload': typeof ConsoleBlueprintsUploadRoute
  '/blueprints/': typeof ConsoleBlueprintsIndexRoute
  '/blueprints/units/$unitId': typeof ConsoleBlueprintsUnitsUnitIdRoute
}
export interface FileRoutesByTo {
  '/example': typeof ExampleRoute
  '/sign-in': typeof SignInRoute
  '/assets': typeof ConsoleAssetsRoute
  '/operators': typeof ConsoleOperatorsRoute
  '/settings': typeof ConsoleSettingsRoute
  '/system-status': typeof ConsoleSystemStatusRoute
  '/work-orders': typeof ConsoleWorkOrdersRoute
  '/': typeof ConsoleIndexRoute
  '/blueprints/structure': typeof ConsoleBlueprintsStructureRoute
  '/blueprints/subcontractors': typeof ConsoleBlueprintsSubcontractorsRoute
  '/blueprints/units': typeof ConsoleBlueprintsUnitsRouteWithChildren
  '/blueprints/upload': typeof ConsoleBlueprintsUploadRoute
  '/blueprints': typeof ConsoleBlueprintsIndexRoute
  '/blueprints/units/$unitId': typeof ConsoleBlueprintsUnitsUnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_console': typeof ConsoleRouteWithChildren
  '/example': typeof ExampleRoute
  '/sign-in': typeof SignInRoute
  '/_console/assets': typeof ConsoleAssetsRoute
  '/_console/blueprints': typeof ConsoleBlueprintsRouteWithChildren
  '/_console/operators': typeof ConsoleOperatorsRoute
  '/_console/settings': typeof ConsoleSettingsRoute
  '/_console/system-status': typeof ConsoleSystemStatusRoute
  '/_console/work-orders': typeof ConsoleWorkOrdersRoute
  '/_console/': typeof ConsoleIndexRoute
  '/_console/blueprints/structure': typeof ConsoleBlueprintsStructureRoute
  '/_console/blueprints/subcontractors': typeof ConsoleBlueprintsSubcontractorsRoute
  '/_console/blueprints/units': typeof ConsoleBlueprintsUnitsRouteWithChildren
  '/_console/blueprints/upload': typeof ConsoleBlueprintsUploadRoute
  '/_console/blueprints/': typeof ConsoleBlueprintsIndexRoute
  '/_console/blueprints/units/$unitId': typeof ConsoleBlueprintsUnitsUnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/example'
    | '/sign-in'
    | '/assets'
    | '/blueprints'
    | '/operators'
    | '/settings'
    | '/system-status'
    | '/work-orders'
    | '/'
    | '/blueprints/structure'
    | '/blueprints/subcontractors'
    | '/blueprints/units'
    | '/blueprints/upload'
    | '/blueprints/'
    | '/blueprints/units/$unitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/example'
    | '/sign-in'
    | '/assets'
    | '/operators'
    | '/settings'
    | '/system-status'
    | '/work-orders'
    | '/'
    | '/blueprints/structure'
    | '/blueprints/subcontractors'
    | '/blueprints/units'
    | '/blueprints/upload'
    | '/blueprints'
    | '/blueprints/units/$unitId'
  id:
    | '__root__'
    | '/_console'
    | '/example'
    | '/sign-in'
    | '/_console/assets'
    | '/_console/blueprints'
    | '/_console/operators'
    | '/_console/settings'
    | '/_console/system-status'
    | '/_console/work-orders'
    | '/_console/'
    | '/_console/blueprints/structure'
    | '/_console/blueprints/subcontractors'
    | '/_console/blueprints/units'
    | '/_console/blueprints/upload'
    | '/_console/blueprints/'
    | '/_console/blueprints/units/$unitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsoleRoute: typeof ConsoleRouteWithChildren
  ExampleRoute: typeof ExampleRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example': {
      id: '/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/': {
      id: '/_console/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/work-orders': {
      id: '/_console/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof ConsoleWorkOrdersRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/system-status': {
      id: '/_console/system-status'
      path: '/system-status'
      fullPath: '/system-status'
      preLoaderRoute: typeof ConsoleSystemStatusRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/settings': {
      id: '/_console/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/operators': {
      id: '/_console/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof ConsoleOperatorsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/blueprints': {
      id: '/_console/blueprints'
      path: '/blueprints'
      fullPath: '/blueprints'
      preLoaderRoute: typeof ConsoleBlueprintsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/assets': {
      id: '/_console/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof ConsoleAssetsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/blueprints/': {
      id: '/_console/blueprints/'
      path: '/'
      fullPath: '/blueprints/'
      preLoaderRoute: typeof ConsoleBlueprintsIndexRouteImport
      parentRoute: typeof ConsoleBlueprintsRoute
    }
    '/_console/blueprints/upload': {
      id: '/_console/blueprints/upload'
      path: '/upload'
      fullPath: '/blueprints/upload'
      preLoaderRoute: typeof ConsoleBlueprintsUploadRouteImport
      parentRoute: typeof ConsoleBlueprintsRoute
    }
    '/_console/blueprints/units': {
      id: '/_console/blueprints/units'
      path: '/units'
      fullPath: '/blueprints/units'
      preLoaderRoute: typeof ConsoleBlueprintsUnitsRouteImport
      parentRoute: typeof ConsoleBlueprintsRoute
    }
    '/_console/blueprints/subcontractors': {
      id: '/_console/blueprints/subcontractors'
      path: '/subcontractors'
      fullPath: '/blueprints/subcontractors'
      preLoaderRoute: typeof ConsoleBlueprintsSubcontractorsRouteImport
      parentRoute: typeof ConsoleBlueprintsRoute
    }
    '/_console/blueprints/structure': {
      id: '/_console/blueprints/structure'
      path: '/structure'
      fullPath: '/blueprints/structure'
      preLoaderRoute: typeof ConsoleBlueprintsStructureRouteImport
      parentRoute: typeof ConsoleBlueprintsRoute
    }
    '/_console/blueprints/units/$unitId': {
      id: '/_console/blueprints/units/$unitId'
      path: '/$unitId'
      fullPath: '/blueprints/units/$unitId'
      preLoaderRoute: typeof ConsoleBlueprintsUnitsUnitIdRouteImport
      parentRoute: typeof ConsoleBlueprintsUnitsRoute
    }
  }
}

interface ConsoleBlueprintsUnitsRouteChildren {
  ConsoleBlueprintsUnitsUnitIdRoute: typeof ConsoleBlueprintsUnitsUnitIdRoute
}

const ConsoleBlueprintsUnitsRouteChildren: ConsoleBlueprintsUnitsRouteChildren =
  {
    ConsoleBlueprintsUnitsUnitIdRoute: ConsoleBlueprintsUnitsUnitIdRoute,
  }

const ConsoleBlueprintsUnitsRouteWithChildren =
  ConsoleBlueprintsUnitsRoute._addFileChildren(
    ConsoleBlueprintsUnitsRouteChildren,
  )

interface ConsoleBlueprintsRouteChildren {
  ConsoleBlueprintsStructureRoute: typeof ConsoleBlueprintsStructureRoute
  ConsoleBlueprintsSubcontractorsRoute: typeof ConsoleBlueprintsSubcontractorsRoute
  ConsoleBlueprintsUnitsRoute: typeof ConsoleBlueprintsUnitsRouteWithChildren
  ConsoleBlueprintsUploadRoute: typeof ConsoleBlueprintsUploadRoute
  ConsoleBlueprintsIndexRoute: typeof ConsoleBlueprintsIndexRoute
}

const ConsoleBlueprintsRouteChildren: ConsoleBlueprintsRouteChildren = {
  ConsoleBlueprintsStructureRoute: ConsoleBlueprintsStructureRoute,
  ConsoleBlueprintsSubcontractorsRoute: ConsoleBlueprintsSubcontractorsRoute,
  ConsoleBlueprintsUnitsRoute: ConsoleBlueprintsUnitsRouteWithChildren,
  ConsoleBlueprintsUploadRoute: ConsoleBlueprintsUploadRoute,
  ConsoleBlueprintsIndexRoute: ConsoleBlueprintsIndexRoute,
}

const ConsoleBlueprintsRouteWithChildren =
  ConsoleBlueprintsRoute._addFileChildren(ConsoleBlueprintsRouteChildren)

interface ConsoleRouteChildren {
  ConsoleAssetsRoute: typeof ConsoleAssetsRoute
  ConsoleBlueprintsRoute: typeof ConsoleBlueprintsRouteWithChildren
  ConsoleOperatorsRoute: typeof ConsoleOperatorsRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleSystemStatusRoute: typeof ConsoleSystemStatusRoute
  ConsoleWorkOrdersRoute: typeof ConsoleWorkOrdersRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAssetsRoute: ConsoleAssetsRoute,
  ConsoleBlueprintsRoute: ConsoleBlueprintsRouteWithChildren,
  ConsoleOperatorsRoute: ConsoleOperatorsRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleSystemStatusRoute: ConsoleSystemStatusRoute,
  ConsoleWorkOrdersRoute: ConsoleWorkOrdersRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConsoleRoute: ConsoleRouteWithChildren,
  ExampleRoute: ExampleRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
