/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsoleIndexRouteImport } from './routes/_console/index'
import { Route as ConsoleExampleRouteImport } from './routes/_console/example'
import { Route as ConsoleProjectsRouteImport } from './routes/_console/projects'
import { Route as ConsoleSubcontractorsIndexRouteImport } from './routes/_console/subcontractors.index'
import { Route as ConsoleSubcontractorsIdRouteImport } from './routes/_console/subcontractors.$id'
import { Route as ConsoleSubcontractorsNewRouteImport } from './routes/_console/subcontractors.new'

const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleExampleRoute = ConsoleExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleProjectsRoute = ConsoleProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSubcontractorsIndexRoute =
  ConsoleSubcontractorsIndexRouteImport.update({
    id: '/subcontractors/',
    path: '/subcontractors/',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleSubcontractorsIdRoute = ConsoleSubcontractorsIdRouteImport.update({
  id: '/subcontractors/$id',
  path: '/subcontractors/$id',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSubcontractorsNewRoute =
  ConsoleSubcontractorsNewRouteImport.update({
    id: '/subcontractors/new',
    path: '/subcontractors/new',
    getParentRoute: () => ConsoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ConsoleIndexRoute
  '/login': typeof LoginRoute
  '/example': typeof ConsoleExampleRoute
  '/projects': typeof ConsoleProjectsRoute
  '/subcontractors/$id': typeof ConsoleSubcontractorsIdRoute
  '/subcontractors/new': typeof ConsoleSubcontractorsNewRoute
  '/subcontractors/': typeof ConsoleSubcontractorsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/example': typeof ConsoleExampleRoute
  '/projects': typeof ConsoleProjectsRoute
  '/': typeof ConsoleIndexRoute
  '/subcontractors/$id': typeof ConsoleSubcontractorsIdRoute
  '/subcontractors/new': typeof ConsoleSubcontractorsNewRoute
  '/subcontractors': typeof ConsoleSubcontractorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_console': typeof ConsoleRouteWithChildren
  '/login': typeof LoginRoute
  '/_console/example': typeof ConsoleExampleRoute
  '/_console/projects': typeof ConsoleProjectsRoute
  '/_console/': typeof ConsoleIndexRoute
  '/_console/subcontractors/$id': typeof ConsoleSubcontractorsIdRoute
  '/_console/subcontractors/new': typeof ConsoleSubcontractorsNewRoute
  '/_console/subcontractors/': typeof ConsoleSubcontractorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/example'
    | '/projects'
    | '/subcontractors/$id'
    | '/subcontractors/new'
    | '/subcontractors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/example'
    | '/projects'
    | '/'
    | '/subcontractors/$id'
    | '/subcontractors/new'
    | '/subcontractors'
  id:
    | '__root__'
    | '/_console'
    | '/login'
    | '/_console/example'
    | '/_console/projects'
    | '/_console/'
    | '/_console/subcontractors/$id'
    | '/_console/subcontractors/new'
    | '/_console/subcontractors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsoleRoute: typeof ConsoleRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/': {
      id: '/_console/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/example': {
      id: '/_console/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ConsoleExampleRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/projects': {
      id: '/_console/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ConsoleProjectsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/subcontractors/': {
      id: '/_console/subcontractors/'
      path: '/subcontractors'
      fullPath: '/subcontractors/'
      preLoaderRoute: typeof ConsoleSubcontractorsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/subcontractors/$id': {
      id: '/_console/subcontractors/$id'
      path: '/subcontractors/$id'
      fullPath: '/subcontractors/$id'
      preLoaderRoute: typeof ConsoleSubcontractorsIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/subcontractors/new': {
      id: '/_console/subcontractors/new'
      path: '/subcontractors/new'
      fullPath: '/subcontractors/new'
      preLoaderRoute: typeof ConsoleSubcontractorsNewRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleExampleRoute: typeof ConsoleExampleRoute
  ConsoleProjectsRoute: typeof ConsoleProjectsRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleSubcontractorsIdRoute: typeof ConsoleSubcontractorsIdRoute
  ConsoleSubcontractorsNewRoute: typeof ConsoleSubcontractorsNewRoute
  ConsoleSubcontractorsIndexRoute: typeof ConsoleSubcontractorsIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleExampleRoute: ConsoleExampleRoute,
  ConsoleProjectsRoute: ConsoleProjectsRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleSubcontractorsIdRoute: ConsoleSubcontractorsIdRoute,
  ConsoleSubcontractorsNewRoute: ConsoleSubcontractorsNewRoute,
  ConsoleSubcontractorsIndexRoute: ConsoleSubcontractorsIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConsoleRoute: ConsoleRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
